name: coriv
description: A new Flutter application.
version: 1.2.0

environment:
  sdk: '>=2.15.0 <3.0.0'
  flutter: '>=1.22.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  flutter_webrtc: ^0.9.23
  shared_preferences: ^2.0.7
  http: ^0.13.3
  path_provider: ^2.0.2
  logging: ^1.1.1
  convert: ^3.1.1
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  ini: ^2.1.0
  shelf_web_socket: ^1.0.3
  shelf_static: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
